YourSOP/config/routes.rb
Rails.application.routes.draw do

  resources :topics

  resources :organisations do
    collection do
      get :invite
      get :users
      delete :remove_user
      get :edit_user
      put :update_user
      get :services
      put :update_service
      get :import
      put :update_sops
      get :browse
    end
    put :save_current_organisation#, :on => :collection

    get :autocomplete_user_email, :on => :collection
  end

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users

  resources :documents do
    collection do
      put :save_role_response, as: :save_role_response
    end
  end

  resources :risks

  resources :audits do
    collection do
      put :save_audit_response, as: :save_audit_response
    end
  end

  resources :topics

  get 'documents/index'
  get 'documents/dashboard'
  match 'documents', to: 'documents#handle_status', via: :put, as: :handle_status
  match 'documents/:id/revise' => 'documents#revise', via: :get, as: 'revise'

  match 'organisations/save_current_organisation', to: 'organisations#save_current_organisation', via: :post
  
  match "organisations/accept_organisation_invitation", to: 'organisations#accept_organisation_invitation', via: :post
  match "organisations/decline_organisation_invitation", to: 'organisations#decline_organisation_invitation', via: :post

  match "organisations/accept_organisation_application", to: 'organisations#accept_organisation_application', via: :post
  match "organisations/decline_organisation_application", to: 'organisations#decline_organisation_application', via: :post

  match 'organisations/invite', to: 'organisations#inviteSubmission', via: :post
  match 'organisations/join/:id' => 'organisations#join', via: :get

  match "revert_to_draft" => "documents#revert_to_draft", via: :post, as: 'revert_to_draft'

  root to: "home#index"

  match 'documents/:id/revision/:major-:minor' => 'documents#revision', via: :get, as: 'revision'

  match 'documents/:id/compare/:revision1/:revision2' => 'documents#compare', via: :get, as: 'compare'

  mount Commontator::Engine => '/commontator'

  get 'risks/index'
  match 'risks', to: 'risks#handle_listRisks', via: :put, as: "handle_listRisks"
  match 'list_risks' => 'risks#list_risks', via: :post, as: 'list_risks'

  match 'audits', to: 'audits#handle_audit_status', via: :put, as: :handle_audit_status
  match 'list_audits' => 'audits#list_audits', via: :post, as: 'list_audits'
  match 'audits/:id/result' => 'audits#result', via: :get, as: 'result'
  match "start_audit" => "audits#start_audit", via: :post, as: 'start_audit'

  get 'home/index'

  resources :home, only: [:index] do
    member do
      post :mark_as_read
    end
    collection do
      put :save_audit_action, as: :save_audit_action
    end
  end

  get 'dashboard/index'
  match "audit_this_year" => "dashboard#audit_this_year", via: :get, as: 'audit_this_year'
  match "topic_risk_trend" => "dashboard#topic_risk_trend", via: :get, as: 'topic_risk_trend'
  match "document_status" => "dashboard#document_status", via: :get, as: 'document_status'
  match "audit_result" => "dashboard#audit_result", via: :get, as: 'audit_result'
  match "compliance_rate" => "dashboard#compliance_rate", via: :get, as: 'compliance_rate'

end

YourSOP/app/models/audit.rb
class Audit < ActiveRecord::Base
  acts_as_commontable

	has_many :audits_practices
	has_many :audit_approvals
	has_many :audit_reviews
	has_many :audit_comments
	has_many :users, through: :audit_approvals
	has_many :users, through: :audit_reviews
	has_many :audits_practices_actions, through: :audits_practices

	belongs_to :topic
	belongs_to :user
	accepts_nested_attributes_for :audits_practices, :allow_destroy => true

	validates_presence_of :audits_practices
	validates_presence_of :audit_reviews
	validates_presence_of :audit_approvals

private

def check_valid_date
	if self.end_date < self.start_date
		errors.add(:end_date, "Invalid Date, end date can't less than start date")
	end
end



end

YourSOP/app/models/user.rb
class User < ActiveRecord::Base
  acts_as_commontator
  acts_as_messageable

  has_many :auditers
  has_many :audits, through: :auditers
  has_many :organisations
  has_many :approvals
  has_many :reviews
  has_many :trainees
  has_many :documents
  has_many :organisation_users
  has_many :audit_comments
  has_many :users

  has_many :documents, through: :approvals
  has_many :documents, through: :readers
  has_many :documents, through: :reviews
  #has_many :documents, through: :trainees
  has_many :organisations, through: :organisation_users
  has_many :audits_practices_actions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

 #validates_uniqueness_of :email
 #validates :email, presence: true

 validates :name, presence: true, on: :create
 validates_uniqueness_of :name

 #validates :encrypted_password, presence: true



  def mailboxer_email(object)
    email
  end

end

YourSOP/app/controllers/audits_controller.rb
class AuditsController < ApplicationController

  before_action :check_current_organisation 
  #before_action :check_current_user_is_quality,  except: :index

  @@audits_practices_result = Hash[ "Green", 1, "Amber", 2, "Red", 3 ]

  @@STATUS_DRAFT = 0    
  @@STATUS_FOR_REVIEW = 1
  @@STATUS_FOR_APPROVAL = 2
  @@STATUS_APPROVED = 3
  @@STATUS_AUDITING = 4
  @@STATUS_FINISHED = 5

  # GET /audits
  # GET /audits.json
  def index
    if get_status_filter == nil
      set_status_filter @@STATUS_DRAFT
    end

    @audits = get_audits

    @draft_count = get_audits_count @@STATUS_DRAFT
    @review_count = get_audits_count @@STATUS_FOR_REVIEW
    @approval_count = get_audits_count @@STATUS_FOR_APPROVAL
    @approved_count = get_audits_count @@STATUS_APPROVED
    @auditing_count = get_audits_count @@STATUS_AUDITING
    @finished_count = get_audits_count @@STATUS_FINISHED

    @status = get_status_filter

  end

  def list_audits
    @audits = get_audits
    render 'list.js.erb'
  end

  def show
    @audit = Audit.find(params[:id])
    
    setup_show
  end

  def new
    id = params[:id]
     #check if active audit exist
    if check_if_active_audit_exist id
      redirect_to risks_path, notice: 'There is already an active audit, a topic can only one active audit.'
    end

    if !check_if_topic_has_risk_assessment id
      redirect_to risks_path, notice: 'Please assess risks of this topic first.'
    end

    @topic = Topic.find(id)
    @topic_id = @topic.id
    @risk = Risk.where(topic_id: @topic.id, status: 1).first
    @audit = Audit.where(topic_id: @topic.id, status: -1).first

   setup_new
  end

  def edit
    @audit = Audit.find(params[:id])
    @topic = Topic.find(@audit.topic_id)
    @topic_id = @topic.id
    @risk = Risk.where(topic_id: @topic.id, status: 1).first
    
    setup_edit
  end

  def create
    @audit = Audit.new(audit_params)
    @topic = @audit.topic
    @topic_id = @audit.topic_id
    @audit.user_id = current_user.id
    @risk = Risk.where(topic_id: @topic.id, status: 1).first
    risk = Risk.find_by_topic_id_and_status(@audit.topic_id, 1);
    @audit.risk_id = risk.id
    @topic = Topic.find(@audit.topic_id)
    
    
    
    if params[:reviews] != nil
      new_reviewer_ids = params[:reviews]
      new_reviewer_ids.each do |blah, action|
        next if blah.blank?
        blah2 = AuditReview.new
        blah2.user_id = blah.to_i
        blah2.status = 0
        @audit.audit_reviews << blah2
      end
    end

    if params[:approvals] != nil
      new_approver_ids = params[:approvals]
      new_approver_ids.each do |blah, action|
        next if blah.blank?
        blah2 = AuditApproval.new
        blah2.user_id = blah.to_i
        blah2.audit = @audit
        blah2.status = 0
        @audit.audit_approvals << blah2

        
      end
    end

    saved = false
    if auditing?
      @audit.status = @@STATUS_FOR_REVIEW
      saved = @audit.save
      if saved
        send_initial_mail
      end
    else
      @audit.status = @@STATUS_DRAFT
      saved = @audit.save!(:validate => false)
    end

    if saved
      update_audit_doc_version @audit.id
      redirect_to @audit
    else
      setup_new
      render action: 'new'
      return
    end
  end

  def update
    @audit = Audit.find(params[:id])
    @topic = Topic.find(@audit.topic_id)
    if draft? or auditing?
      reviews =  @audit.audit_reviews.find_by_audit_id(@audit.id)
      if reviews.present?
        reviews.destroy
      end

      approvals = @audit.audit_approvals.find_by_audit_id(@audit.id)
      if approvals.present?
        approvals.destroy
      end
      @audit.reload

      if params[:reviews] != nil
        new_reviewer_ids = params[:reviews]
        new_reviewer_ids.each do |blah, action|
          next if blah.blank?
          blah2 = AuditReview.new
          blah2.user_id = blah.to_i
          blah2.status = 0
          @audit.audit_reviews << blah2
        end
      end

      if params[:approvals] != nil
        new_approver_ids = params[:approvals]
        new_approver_ids.each do |blah, action|
          next if blah.blank?
          blah2 = AuditApproval.new
          blah2.user_id = blah.to_i
          blah2.audit = @audit
          blah2.status = 0
          @audit.audit_approvals << blah2
        end
      end

    end

    saved = false
    if draft? or temp_save?
      @audit.attributes = audit_params.merge(:end_date => nil)
      saved = @audit.save!(:validate => false)
    elsif auditing?
      saved = @audit.update(audit_params.merge(:status => @@STATUS_FOR_REVIEW))
      if saved
        send_initial_mail
      end
    elsif publish?
      @audit.attributes = audit_params.merge(:status => @@STATUS_FINISHED)
      saved = @audit.save!(:validate => false)
      if saved
        @topic = Topic.find(@audit.topic_id)
        @topic.update(last_audit_date: @audit.end_date)
      end
    end

    if saved
      update_audit_doc_version @audit.id
      redirect_to audits_path
    else
      if draft? or auditing?
        @topic = Topic.find(@audit.topic_id)
        @topic_id = @topic.id
        @risk = Risk.where(topic_id: @topic.id, status: 1).first
        setup_edit
        render action: 'edit', :id => @audit.id, alert: 'Audit ould not be updated.'
      elsif publish? or temp_save
        @audit.audits_practices.each do |p|
           p.audits_practices_actions.build
         end
        @topic = Topic.find(@audit.topic_id)        
        @risk = Risk.where(topic_id: @topic.id, status: 1).first        
        @audits_practices_result = @@audits_practices_result       
        @topic_id = @topic.id       
        @start_date = @audit.start_date   
        setup_result
        render action: 'result', :id => @audit.id, alert: 'Audit ould not be saved.'
      end
      
    end

  end

  def result
     @audit = Audit.find(params[:id])
     @audit.audits_practices.each do |p|
       p.audits_practices_actions.build
     end
    @topic = Topic.find(@audit.topic_id)		    
    @risk = Risk.where(topic_id: @topic.id, status: 1).first		    
    @audits_practices_result = @@audits_practices_result		   
    @topic_id = @topic.id		    
    @start_date = @audit.start_date		   
    setup_result
  end

  def setup_result
    @users_to_select = []
    users = OrganisationUser.where(organisation_id: get_current_organisation.id, accepted: true)
    users.each do |ou|
      if ou.user == nil
        raise ou.user
      end
      @users_to_select << ou.user
    end
  end


  def handle_audit_status
    if params[:status] != nil # view audits with different status
      set_status_filter risk_status_to_int params[:status]
      @new_audits = get_audits
      respond_to do |format|
        format.js
      end
    end
  end

  def start_audit
    if (params[:id] == nil) 
      return
    end

    audit = Audit.find(params[:id].to_i)
    if audit.status != @@STATUS_APPROVED or !is_quality(OrganisationUser.where(user: current_user, organisation: @current_organisation)[0].user_type)
      flash[:danger] = 'You cannot perform this operation.'
      render :js => "window.location = '/audits'"
    end
    audit.update(status: @@STATUS_AUDITING, start_date: Time.now);

    flash[:success] = 'You have maked this audit started.'
    render :js => "window.location = '/audits'"

  end

  #def restart_audit
  #    @audit = Audit.find(params[:id])
  #    if @audit.user != current_user
  #      flash[:warning] = 'You can only revise documents created by you.'
  #      redirect_to action: 'index'
  #    end

  #    if @audit.status != @@STATUS_FINISHED
  #     flash[:warning] = 'You can only revise documents that are in the Effective state.'
  #      redirect_to action: 'index'
  #    end
  #    redirect_to edit_audit_path
  #end
  
  def save_audit_response
    	if params[:decline] == nil    # require a digital signature to approve/mark as reviewed
      # password is filtered in params log by Devise gem (not visible in params array)
      if params[:email] != current_user.email || !current_user.valid_password?(params[:password])   # if wrong email or password
        if params[:review] != nil
          @audit = AuditReview.find(params[:relation_id].to_i).audit
          setup_show
          flash[:danger] = 'Incorrect email or password.'
          redirect_to audit_path(@audit.id)
          return
        else
          @audit = AuditApproval.find(params[:relation_id].to_i).audit
          setup_show
          flash[:danger] = 'Incorrect email or password.'
          redirect_to audit_path(@audit.id)
          return
        end
      end
    end

    success = ''
    if params[:approve] != nil
      a = AuditApproval.find params[:relation_id].to_i
      a.status = 1
      a.save
      success = 'You have approved this audit.'

      # if all approvers have approved the audit, make it effective
      approvals = AuditApproval.where(audit: a.audit).where.not(status: 1)   # approvals where status != approved
      @audit = a.audit
      @topic = Topic.find(@audit.topic_id)
      if approvals.empty?
        @audit.update(status: @@STATUS_APPROVED)    # audit is now approved
        Notifier.audit_status(User.find(@audit.user_id).email, @topic.name, 'Approved').deliver_later

        # TODO: Send email to creator of audit to notify of approval
        #Notifier.doc_status(User.find(document.user_id).email,document.title,'Approved').deliver_now

      end
    elsif params[:decline] != nil
      a = AuditApproval.find params[:relation_id].to_i
      @audit = a.audit
      @topic = Topic.find(@audit.topic_id)
      a.status = 2
      a.save
      
      #if one reject, just mark audit to draft, 
      @audit = Audit.find(a.audit_id)
      @audit.update(status: @@STATUS_DRAFT)
      Notifier.audit_status(User.find(@audit.user_id).email, @topic.name, "Decline by #{a.user.email}").deliver_later
      
      #and cancel other approvals
      approvals = AuditApproval.where(audit: a.audit, status: 0)
      approvals.each do |a|

YourSOP/app/helpers/audits_helper.rb
module AuditsHelper
	def topic_status_to_string status
        if status == 0
            'Draft'
        elsif status == 1
            'For Review'
        elsif status == 2
            'For Approval'
        elsif status == 3
            'Approved'
        elsif status == 4
            'Auditing'
        elsif status == 5
            'Finished'
        else
            'Unknown'
        end
     end

     def audit_result_to_string result
        if result == 1
            'Green'
        elsif result == 2
            'Amber'
        elsif result == 3
            'Red'
        else
            'Unknown'
        end
     end

end

YourSOP/app/views/audits/_form.erb
<div class="container-fluid">
  <dl class="dl-horizontal">
    <dt><strong>Topic:</strong></dt>
    <dd><%= @topic.name %></dd>
  </dl>

  <dl class="dl-horizontal">
    <dt><strong>Topic Description:</strong></dt>
    <dd><%= @topic.description %></dd>
  </dl>

  <dl class="dl-horizontal">
    <dt><strong>Documents:</strong></dt>
    <dd>
      <ul>
        <% @risk.topic.documents.where("major_version != '0'").each do |d| %>
          <li><%= link_to d.title, document_path(d.id), target: "_blank" %></li>
        <% end %>
      </ul>
    </dd>
  </dl>

  <dl class="dl-horizontal">
    <dt><strong>Risk Description:</strong></dt>
    <dd><%= raw @risk.desc %></dd>
  </dl>

  <dl class="dl-horizontal">
    <dt><strong>Risk Score:</strong></dt>
    <dd><%= @risk.score %></dd>
  </dl>

  <dl class="dl-horizontal">
    <dt><strong>Risk Details:</strong></dt>
    <dd>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Title</th>
            <th>Impact</th>
            <th>Likelihood</th>
            <th>Score</th>
          </tr>
        </thead>
        <tbody>
           <% @risk.risks_details.each do |d| %>
            <tr>
              <td><%= d.title %></td>
              <td><%= risk_impact_to_string d.impact %></td>
              <td><%= risk_likelihood_to_string d.likelihood %></td>
              <td><%= d.score %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </dd>
  </dl>
</div>
  
<%= bootstrap_nested_form_for(audit, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-11") do |form| %>
    <%= form.alert_message "Please fix the errors below." %>
    <%= form.hidden_field :topic_id, value: @topic_id %>
    <%= form.hidden_field :end_date, value: :end_date %>
    <%= form.hidden_field :result, value: :result %>
    <%= form.hidden_field :status, value: :status %>

    

    <%#= form.date_field :start_date, value: form.object.start_date.to_date, control_col: "col-sm-3"  %>
    <div class="form-group"> 
        <label class="control-label col-sm-2" for="">Practices:</label>
            <div class="col-sm-10">
                <div class="form-inline">
                    <%= form.fields_for :audits_practices do |f| %>
                        <%= f.text_area :observation, label: 'Description', :rows => 4, :cols => 60 %>

                        <%= f.collection_check_boxes :document_ids, @risk.topic.documents.where("major_version != '0'"), :id, :title, label: "Source" %>
                        <%= f.check_box :_destroy %>
                    <% end %>
                    <%= form.link_to_add "Add", :audits_practices %>

                 </div>
        </div>
       
    </div>

    <dl class="dl-horizontal">
      <dt><strong>Select Users for<br/> Review </strong></dt>
       <dd> 
          <%= render partial: 'documents/user_select', locals: {params_hash: 'reviews', selected_users: @existing_reviewer_ids, users: @current_organisation.users } %>
      </dd>
    </dl>
                             
    <dl class="dl-horizontal">
      <dt><strong>Select Users for<br/> Approval </strong></dt>
       <dd>
          <%= render partial: 'documents/user_select', locals: {params_hash: 'approvals', selected_users: @existing_approver_ids, users: @current_organisation.users } %>
      </dd>
    </dl>
    
    <%= form.form_group do %>
     <%= form.submit "Send For Review", class: "btn btn-primary", data: {disable_with: "Saving..."} %>
     <%= form.submit "Save as Draft", class: "btn btn-default", data: {disable_with: "Saving..."} %>
    <% end %>
<% end %>

YourSOP/app/views/audits/_list.erb
<div id="audits_list">
<table class="table table-striped">
  <thead>
  <tr>
    <th>
      Topic
    </th>
    <th>
      Start Date
    </th>
    <th>
      End Date
    </th>
    <th>
      Created By
    </th>
    <th>
      Status 
    </th>
    <th>
      Result
    </th>
    <th>
      Actions
    </th>
  </tr>
  </thead>
  <tbody>
  <% audits.each do |a| %>
      <tr>
        <td>
          <%= link_to a.topic.name, audit_path(a.id) %>
        </td>
        
        <td>
          <%= a.start_date %>
        </td>
        <td>
          <%= a.end_date %>
        </td>
        <td>
          <%= a.user.email %>
        </td>
        <td>
          <%= topic_status_to_string a.status %>
        </td>
        <td><%= audit_result_to_string a.result %></td>
        <td>
            <%= link_to "Fill in Result", result_path(:id => a.id), :class => "btn-link" if a.status == 4 and is_current_user_quality_or_owner %>
            <%= link_to "Start Audit", start_audit_path(:id => a.id), method: :post, remote: true, data: { confirm: 'Are you sure to start this aduit? this will make the audit start today.' }, :class => "btn-link" if a.status == 3 and is_current_user_quality_or_owner %>
            <%= link_to "Edit", edit_audit_path(:id => a.id), :class => "btn-link" if a.status == 0 and a.user_id == @current_user.id %>
            <%= link_to "Review", audit_path(:id => a.id), :class => "btn-link" if a.status == 1 and a.audit_reviews.where(status: 0, user_id: @current_user.id).count() > 0 %>
            <%= link_to "Approve", audit_path(:id => a.id), :class => "btn-link" if a.status == 2 and a.audit_approvals.where(status: 0, user_id: @current_user.id).count() > 0 %>
            <% if a.status == 5 %>
            <%= link_to "View Audit Report", audit_path(a.id), :class => "btn-link" %>
            <%#= link_to "Restart Audit", restart_audit_path(:id => a.id), :class => "btn-link" if a.user_id == @current_user.id %>
            <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
</div>

YourSOP/app/views/audits/edit.html.erb
<h2>Edit Audit</h2>
<%= render partial: 'form', locals: {audit: @audit }%>

YourSOP/app/views/audits/handle_audit_status.js.erb
$("#audits_list").html("<%= escape_javascript(render partial: 'list', locals: { audits: @new_audits } ) %>");

YourSOP/app/views/audits/index.html.erb
<h1>Audit Management</h1>

<ul class="nav nav-tabs" id="document_filter_buttons" >
  <li id="listRisks" role="presentation" class="active" ><%= link_to "Audits", list_audits_path, method: :post, remote: true %></li>
</ul>


</div>
</div>

<div class="container">

<%= form_for :audits, method: :put, remote: true do |f| %>

<div class="col-md-2">
    <div class="btn-group-vertical" id="status_filter_buttons">
          <br />
          <% 
            active = ""
            if @status == 0
              active = "active btn-warning"
            end 
          %>
          <%= f.submit "Draft" + @draft_count, class: "btn btn-primary " + active, align: "right", name: "status", id: "0" %>

          <% 
            active = ""
            if @status == 1
              active = "active btn-warning"
            end 
          %>
          <%= f.submit "For review" + @review_count, class: "btn btn-primary " + active, name: "status", id: "1" %>

          <% 
            active = ""
            if @status == 2
              active = "active btn-warning"
            end 
          %>
          <%= f.submit "For approval" + @approval_count, class: "btn btn-primary " + active, name: "status", id: "2" %>

          <% 
            active = ""
            if @status== 3
              active = "active btn-warning"
            end 
          %>
          <%= f.submit "Approved" + @approved_count, class: "btn btn-primary " + active, name: "status", id: "3" %>                  
          <% 
            active = ""
            if @status== 4
              active = "active btn-warning"
            end 
          %>
          <%= f.submit "Auditing" + @auditing_count, class: "btn btn-primary " + active, name: "status", id: "4" %>

          <% 
            active = ""
            if @status == 5
              active = "active btn-warning"
            end 
          %>
          <%= f.submit "Finished" + @finished_count, class: "btn btn-primary " + active, name: "status", id: "5" %> 
    </ul>
  </div>
</div>

<% end %>

<!-- tab content -->
<div class="col-md-10">
  <div class="tab-content" id="tab_content_list">
    <div class="tab-pane active text-style" id="tab0">
        <%= render partial: 'list', locals: {audits: @audits} %>    
    </div>
</div>
</div>
</div>


  

YourSOP/app/views/audits/new.html.erb
<h2>Create Audit</h2>
<%= render partial: 'form', locals: {audit: @audit }%>

YourSOP/app/views/audits/result.html.erb
<div class="container-fluid">
  <dl class="dl-horizontal">
    <dt><strong>Topic</strong></dt>
    <dd><%= @topic.name %></dd>
  </dl>

  <dl class="dl-horizontal">
    <dt><strong>Topic Description</strong></dt>
    <dd><%= @topic.description %></dd>
  </dl>

  <dl class="dl-horizontal">
    <dt><strong>SOPs</strong></dt>
    <dd>
      <ul>
        <% @risk.topic.documents.each do |d| %>
          <li><%= link_to d.title, document_path(d.id), target: "_blank" %></li>
        <% end %>
      </ul>
    </dd>
  </dl>

  <dl class="dl-horizontal">
    <dt><strong>Risk Description</strong></dt>
    <dd><%= raw @risk.desc %></dd>
  </dl>

  <dl class="dl-horizontal">
    <dt><strong>Risk Score</strong></dt>
    <dd><%= @risk.score %></dd>
  </dl>

  <dl class="dl-horizontal">
    <dt><strong>Risk Details</strong></dt>
    <dd>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Title</th>
            <th>Impact</th>
            <th>Likelihood</th>
            <th>Score</th>
          </tr>
        </thead>
        <tbody>
           <% @risk.risks_details.each do |d| %>
            <tr>
              <td><%= d.title %></td>
              <td><%= risk_impact_to_string d.impact %></td>
              <td><%= risk_likelihood_to_string d.likelihood %></td>
              <td><%= d.score %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </dd>
  </dl>


  <%= bootstrap_nested_form_for(@audit, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-11") do |form| %>
      <%= form.hidden_field :topic_id, value: @topic_id %>
      <%= form.hidden_field :result, value: :result %>
       <%= form.alert_message "Please fix the errors below." %>

      <%= form.date_field :start_date, value: @start_date.strftime('%Y-%m-%d'), control_col: "col-sm-3", readonly: true  %>


        <table class="table table-bordered">
          <thead>
            <tr>
              <th class="col-sm-2">Description</th>
              <th class="col-sm-2">Source</th>
              <th class="col-sm-3">Evidence</th>
              <th class="col-sm-3">Actions</th>
              <th class="col-sm-2">Result</th>
            </tr>
          </thead>
          <tbody>

            <%= form.fields_for :audits_practices do |p| %>
              <tr>
                <td><%= p.object.observation %></td>
                <td>
                  <% p.object.documents.each do |s| %>
                      <%= link_to s.title, document_path(s.id), target: "_blank" %>
                  <% end %>
                </td>
                <td>
                  <%= p.text_area :evidence, hide_label: true, :class => "tinymce form-control", :rows => 6, :cols => 20 %>
                  <br />
                  <%= p.file_field :attachment %>
                </td>
                <td>
                  <div class="form-horizontal well ">
                    <input type="hidden" value="<%= p.object.id %>" />
                    <%= p.fields_for :audits_practices_actions do |f| %>
                        <%= f.text_area :action, :rows => 4, :cols => 20, help: "If no action required, leave this empty."  %>
                        <%= f.collection_select :user_id, @users_to_select, :id, :email, prompt: "Please Select" %>
                        <%= f.hidden_field :status, value: 0 %>
                        <% if f.object.persisted? %>
                          <%= f.check_box :_destroy %>
                        <% end %>
                    <% end %>
                    <%= p.link_to_add "Add", :audits_practices_actions %>

                 </div>
                </td>
                <td><%= p.select :result, @audits_practices_result, hide_label: true %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    <div class="alert alert-dismissible alert-danger" id="alert">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <p>The final result should not be Green as one or more practices are not Green!</p>
    </div>
    <%= form.date_select :end_date, value: :end_date, start_year: Date.current.year, use_month_numbers: true, control_col: "col-sm-3"  %>
    <%= form.select :result, @audits_practices_result, control_col: "col-sm-3" %>

      <%= form.form_group do %>
        <%= form.submit "Publish Audit", class: "btn btn-primary" %>
        <%= form.submit "Temparory Save", class: "btn btn-default" %>
      <% end %>
    <% end %>

</div>