YourSOP/config/routes.rb
Rails.application.routes.draw do

  resources :topics

  resources :organisations do
    collection do
      get :invite
      get :users
      delete :remove_user
      get :edit_user
      put :update_user
      get :services
      put :update_service
      get :import
      put :update_sops
      get :browse
    end
    put :save_current_organisation#, :on => :collection

    get :autocomplete_user_email, :on => :collection
  end

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users

  resources :documents do
    collection do
      put :save_role_response, as: :save_role_response
    end
  end

  resources :risks

  resources :audits do
    collection do
      put :save_audit_response, as: :save_audit_response
    end
  end

  resources :topics

  get 'documents/index'
  get 'documents/dashboard'
  match 'documents', to: 'documents#handle_status', via: :put, as: :handle_status
  match 'documents/:id/revise' => 'documents#revise', via: :get, as: 'revise'

  match 'organisations/save_current_organisation', to: 'organisations#save_current_organisation', via: :post
  
  match "organisations/accept_organisation_invitation", to: 'organisations#accept_organisation_invitation', via: :post
  match "organisations/decline_organisation_invitation", to: 'organisations#decline_organisation_invitation', via: :post

  match "organisations/accept_organisation_application", to: 'organisations#accept_organisation_application', via: :post
  match "organisations/decline_organisation_application", to: 'organisations#decline_organisation_application', via: :post

  match 'organisations/invite', to: 'organisations#inviteSubmission', via: :post
  match 'organisations/join/:id' => 'organisations#join', via: :get

  match "revert_to_draft" => "documents#revert_to_draft", via: :post, as: 'revert_to_draft'

  root to: "home#index"

  match 'documents/:id/revision/:major-:minor' => 'documents#revision', via: :get, as: 'revision'

  match 'documents/:id/compare/:revision1/:revision2' => 'documents#compare', via: :get, as: 'compare'

  mount Commontator::Engine => '/commontator'

  get 'risks/index'
  match 'risks', to: 'risks#handle_listRisks', via: :put, as: "handle_listRisks"
  match 'list_risks' => 'risks#list_risks', via: :post, as: 'list_risks'

  match 'audits', to: 'audits#handle_audit_status', via: :put, as: :handle_audit_status
  match 'list_audits' => 'audits#list_audits', via: :post, as: 'list_audits'
  match 'audits/:id/result' => 'audits#result', via: :get, as: 'result'
  match "start_audit" => "audits#start_audit", via: :post, as: 'start_audit'

  get 'home/index'

  resources :home, only: [:index] do
    member do
      post :mark_as_read
    end
    collection do
      put :save_audit_action, as: :save_audit_action
    end
  end

  get 'dashboard/index'
  match "audit_this_year" => "dashboard#audit_this_year", via: :get, as: 'audit_this_year'
  match "topic_risk_trend" => "dashboard#topic_risk_trend", via: :get, as: 'topic_risk_trend'
  match "document_status" => "dashboard#document_status", via: :get, as: 'document_status'
  match "audit_result" => "dashboard#audit_result", via: :get, as: 'audit_result'
  match "compliance_rate" => "dashboard#compliance_rate", via: :get, as: 'compliance_rate'

end

YourSOP/app/models/risk.rb
class Risk < ActiveRecord::Base
  	belongs_to :user
  	belongs_to :organisation
    belongs_to :topic
  	has_many :risks_details

  	accepts_nested_attributes_for :risks_details, :allow_destroy => true, reject_if: proc { |attributes| attributes['title'].blank? }
  	
  	validates_presence_of :risks_details
end

YourSOP/app/models/user.rb
class User < ActiveRecord::Base
  acts_as_commontator
  acts_as_messageable

  has_many :auditers
  has_many :audits, through: :auditers
  has_many :organisations
  has_many :approvals
  has_many :reviews
  has_many :trainees
  has_many :documents
  has_many :organisation_users
  has_many :audit_comments
  has_many :users

  has_many :documents, through: :approvals
  has_many :documents, through: :readers
  has_many :documents, through: :reviews
  #has_many :documents, through: :trainees
  has_many :organisations, through: :organisation_users
  has_many :audits_practices_actions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

 #validates_uniqueness_of :email
 #validates :email, presence: true

 validates :name, presence: true, on: :create
 validates_uniqueness_of :name

 #validates :encrypted_password, presence: true



  def mailboxer_email(object)
    email
  end

end

YourSOP/app/controllers/risks_controller.rb
class RisksController < ApplicationController

  
  @@risk_likelihood = Hash[ "Rare/Remote (Actual Frequency: Occurs every 5 years or more. Probability: 1%)", 1, "Unlikely (Actual Frequency: Occurs every 2-5 years. Probability: 10%.)", 2, "Possible (Actual Frequency: Occurs every 1-2 years. Probability: 50%)", 3, "Likely (Actual Frequency: Bimonthly. Probability: 75%.)", 4, "Almost Certain (Actual Frequency: At least monthly. Probability: 99%.)", 5 ]
  @@default_risks = ["Injury", "Service User Experience", "Compliance with Standards (Statutory, Clinical, Professional & Management)", "Objectives/Projects", "Business Continuity", "Adverse publicity/ Reputation", "Financial Loss (per local Contact)", "Environment"]


  before_action :check_current_organisation 
  #before_action :check_current_user_is_quality

  def index
    @topics = get_topics
  end

  def new
    @topic = Topic.find(params[:id])
    @documents = @topic.documents
    @risk = Risk.where(topic_id: @topic.id, status: -1).first
    if @risk == nil
      @risk = Risk.new(:topic_id => @topic.id)
      @@default_risks.each do |r|
        @risk.risks_details.build(title: r, impact: 1, likelihood: 1);
      end
    end
    
    @risk.score = 0
    @current_user_id = current_user.id
    @risk_impact = RisksImpact.all
    @risk_likelihood = @@risk_likelihood
  end

  def create
    @topic = Topic.find(risk_params[:topic_id])
    @risk = @topic.risks.build(risk_params)
    if publishing?
      #update previous risks (topic_id = @risk.topic_id) status value 0
      Risk.where(topic_id: @risk.topic_id.to_s).update_all("status = 0") if publishing?
      @risk.organization_id = get_current_organisation.id
      @risk.status = 1

      #if publishing update topic score = risk.score
      @topic.update(score: @risk.score)

      send_message(current_user.id, "You assessed a topic " + @topic.name + ", now its risk score is " + @risk.score.to_s, Time.now.to_s);
    else
      @risk.status = -1
    end

    if @risk.save
      redirect_to risks_path, notice: 'save succeed!'
    else
      @risk = Risk.where(topic_id: @topic.id, status: -1).first
      if @risk == nil
        @risk = Risk.new(:topic_id => @topic.id)
      end
      @risk.risks_details.build
      @risk.score = 0
      @current_user_id = current_user.id
      @risk_impact = RisksImpact.all
      @risk_likelihood = @@risk_likelihood
      render action: 'new', alert: 'save failed!'
    end
  end

  def update
    @risk = Risk.find(params[:id])

    if publishing?
      #update previous risks (topic_id = @risk.topic_id) status value 0
      Risk.where(topic_id: @risk.topic_id.to_s).update_all("status = 0")
      @risk.status = 1

      #if publishing update topic score = risk.score
      @topic = Topic.find(@risk.topic_id)
      @topic.update(score: @risk.score)

      msg = "Publish succeed!"
    else
      msg = "Save succeed!"
    end

    if @risk.update(risk_params)
      redirect_to risks_path, notice: msg
    else
      redirect_to risks_path, alert: "Operation failed!"
    end
  end

  def show
    @topic = Topic.find(params[:id])
    if params[:risk_id] == nil
      @risk = Risk.where(topic_id: @topic.id, status: 1).first
    else
      @risk = Risk.find(params[:risk_id])
    end

    if @risk == nil
      redirect_to risks_path, alert: "Please assess risks first!"
    end

    @history = Risk.where(topic_id: @topic.id, status: 0).select("created_at, id, score")
  end


  private

    def risk_params
      params.require(:risk).permit(:id, :topic_id, :user_id, :desc, :score, risks_details_attributes: [:id, :title, :impact, :score, :likelihood, :_destroy])
    end

    def get_my_risks
      my_risks = Risk.where(user_id: current_user, organization_id: get_current_organisation, status: get_status_filter) 
      my_risks
    end

    def get_topics
      topics = Topic.where(organisation_id: get_current_organisation, status: 1).order('score is null ASC, score DESC')
    end

    def publishing?
      params[:commit] == "Publish"
    end
end

YourSOP/app/helpers/risks_helper.rb
module RisksHelper

    def if_current_user_is_quality
        if @current_organisation == nil
            return false
        end
        user_type = OrganisationUser.where(user: current_user, organisation: @current_organisation)[0].user_type
        return is_quality(user_type) || is_owner(user_type)
    end

end

YourSOP/app/views/risks/_form.html.erb
<%= bootstrap_nested_form_for(risk, layout: :horizontal, label_col: "col-sm-1") do |form| %>
    <%= form.hidden_field :user_id, value: current_user_id %>
    <%= form.hidden_field :topic_id, value: @topic.id %>
    <div class="row"> 
        <label class="control-label col-sm-1" for="">Risks:</label>
        <div class="col-sm-11">
                <%= form.fields_for :risks_details do |f| %>
                    <div class="well col-sm-12 nested_risk_form">
                        <%= f.text_area :title ,:rows => 2 %>
                        <% title = f.object.title == nil ? '' : f.object.title %>
                        <% 
                            i = risk_impact.where(name: title)
                            if i.count == 0
                                i = risk_impact.where(name: '')
                            end
                        %>
                        <%= f.collection_radio_buttons :impact, i, :value, :desc %>
                        <%= f.select :likelihood, risk_likelihood  %>
                        <%= f.text_field :score, :readonly => true %>
                        <%= f.check_box :_destroy %>
                    </div>
                <% end %>
                <%= form.link_to_add "Add", :risks_details %>
                
        </div>
       
    </div>
    <%= form.text_field :score, :readonly => true %>

    <div class="form-group">
        <label class="control-label col-sm-1" for="">Documents</label>
        <div class="col-sm-10">
            <ul>
                <% documents.where(minor_version: 0).each do |d| %>
                  <li><%= link_to d.title + ' (' + d.major_version + '.0)', document_path(d.id), target: "_blank" %></li>
                <% end %>
            </ul>
        </div>
    </div>
    <%#= form.collection_select :document_ids, Document.where(status: 3).order(:title), :id, :title, {}, {:multiple => true } %>

    <%= form.text_area :desc, :class => "tinymce form-control", :rows => 10, :cols => 120, label: "Rational for Risk Assessment" %>
    <%= tinymce %> 
    <%= form.form_group do %>
      <%= form.submit "Publish", class: "btn btn-primary", data: {disable_with: "Saving..."} %>
      <%= form.submit "Save as Draft", class: "btn btn-default", data: {disable_with: "Saving..."} %>
    <% end %>
<% end %>

YourSOP/app/views/risks/_listRisks.erb
<div id="risks_list">
<table class="table table-striped">
  <thead>
  <tr>
    <th>
      Name
    </th>
    <th>
      Created
    </th>
    <th>
      Updated
    </th>
    <th>
      Score
    </th>
    <th>
      Last Audit Date
    </th>
    <th>
      Actions
    </th>
  </tr>
  </thead>
  <tbody>
  <% topics.each do |t| %>
      <tr>
        <td>
          <%= link_to t.name, risk_path(t.id) %>
        </td>
        <td>
          <%= t.created_at %>
        </td>
        <td>
          <%= t.updated_at %>
        </td>
        <td>
          <%= t.score %>
        </td>
        <td>
          <%= t.last_audit_date %>
        </td>
        <td>
            <%= link_to "Assess Risks", new_risk_path(:id => t.id), :class => "btn-link" %> |
            <%= link_to "Create Audit", new_audit_path(:id => t.id), :class => "btn-link" %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
</div>

YourSOP/app/views/risks/edit.html.erb
<h1>Edit Topic</h1>
<%= render partial: 'form', locals: {risk: @risk, current_user_name: @current_user_name, current_user_id: @current_user_id, risk_impact: @risk_impact, risk_likelihood: @risk_likelihood, documents: @documents} %>

YourSOP/app/views/risks/handle_listRisks.js.erb
$("#risks_list").html("<%= escape_javascript(render partial: 'listRisks', locals: { topics: @topics } ) %>");

YourSOP/app/views/risks/index.html.erb
<h1>Risk Management</h1>

<ul class="nav nav-tabs" id="document_filter_buttons" >
  <li id="listRisks" role="presentation" class="active" ><%= link_to "Topics", list_risks_path, method: :post, remote: true %></li>
</ul>


</div>
</div>

<div class="container">

<!-- tab content -->
<div class="col-md-13">
	<div class="tab-content" id="tab_content_list">
		<div class="tab-pane active text-style" id="tab0">
  			<%= render partial: 'listRisks', locals: {topics: @topics} %>    
		</div>
</div>
</div>
</div>


  

YourSOP/app/views/risks/new.html.erb
<div class="page-header">
  <h1>Risk Assessment Form</h1>
  <h2>Topic: <%= @topic.name %></h2>
</div>
<div class="container">
<%= render partial: 'form', locals: {risk: @risk, current_user_id: @current_user_id, risk_impact: @risk_impact, risk_likelihood: @risk_likelihood, current_user_name: @current_user_name, documents: @documents } %>
</div>

YourSOP/app/views/risks/show.html.erb
<div class="page-header">
  <h1>Risk Assessment Form</h1>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><%= @topic.name %></div>
  <div class="well">
    <p><%= @topic.description %><p/>
  </div>



  <dl class="dl-horizontal">
    <dt><strong>Score:</strong></dt>
    <dd><%= @risk.score %></dd>
  </dl>

  <dl class="dl-horizontal">
    <dt><strong>Description:</strong></dt>
    <dd><%= raw(@risk.desc) %></dd>
  </dl>

  <dl class="dl-horizontal">
    <dt><strong>Documents:</strong></dt>
    <dd>
      <ul>
        <% @risk.topic.documents.each do |d| %>
          <% if d.minor_version.to_i != 0 %>
            <li><%= link_to d.title + " (" + get_effective_document_version(d) + ")", compare_path(d.id, d.document_revisions.find_by_major_version_and_minor_version(d.major_version, 0).id, 0), target: "_blank" %></li>
          <% else %>
            <li><%= link_to d.title + " (" + get_document_version(d) + ")", document_path(d.id), target: "_blank" %></li>
          <% end %>
        <% end %>
      </ul>
    </dd>
  </dl>
  <dl class="dl-horizontal">
    <dt><strong>Assessment History:</strong></dt>
    <dd>
      <ul>
        <% @history.each do |h| %>
          <li><%= link_to h.created_at.to_s + ", Score: " + h.score.to_s, risk_path(@topic.id, :risk_id => h.id), target: "_blank" %></li>
        <% end %>
      </ul>
    </dd>
  </dl>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Risks</div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Impact</th>
        <th>Likelihood</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
       <% @risk.risks_details.each do |d| %>
        <tr>
          <td><%= d.title %></td>
          <td><%= risk_impact_to_string d.impact %></td>
          <td><%= risk_likelihood_to_string d.likelihood %></td>
          <td><%= d.score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


  <br />
  <div class="form-actions">
    <%= link_to 'Back', risks_path, :class => 'btn btn-primary'  %>
  </div>

 