YourSOP/config/routes.rb
Rails.application.routes.draw do

  resources :topics

  resources :organisations do
    collection do
      get :invite
      get :users
      delete :remove_user
      get :edit_user
      put :update_user
      get :services
      put :update_service
      get :import
      put :update_sops
      get :browse
    end
    put :save_current_organisation#, :on => :collection

    get :autocomplete_user_email, :on => :collection
  end

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users

  resources :documents do
    collection do
      put :save_role_response, as: :save_role_response
    end
  end

  resources :risks

  resources :audits do
    collection do
      put :save_audit_response, as: :save_audit_response
    end
  end

  resources :topics

  get 'documents/index'
  get 'documents/dashboard'
  match 'documents', to: 'documents#handle_status', via: :put, as: :handle_status
  match 'documents/:id/revise' => 'documents#revise', via: :get, as: 'revise'

  match 'organisations/save_current_organisation', to: 'organisations#save_current_organisation', via: :post
  
  match "organisations/accept_organisation_invitation", to: 'organisations#accept_organisation_invitation', via: :post
  match "organisations/decline_organisation_invitation", to: 'organisations#decline_organisation_invitation', via: :post

  match "organisations/accept_organisation_application", to: 'organisations#accept_organisation_application', via: :post
  match "organisations/decline_organisation_application", to: 'organisations#decline_organisation_application', via: :post

  match 'organisations/invite', to: 'organisations#inviteSubmission', via: :post
  match 'organisations/join/:id' => 'organisations#join', via: :get

  match "revert_to_draft" => "documents#revert_to_draft", via: :post, as: 'revert_to_draft'

  root to: "home#index"

  match 'documents/:id/revision/:major-:minor' => 'documents#revision', via: :get, as: 'revision'

  match 'documents/:id/compare/:revision1/:revision2' => 'documents#compare', via: :get, as: 'compare'

  mount Commontator::Engine => '/commontator'

  get 'risks/index'
  match 'risks', to: 'risks#handle_listRisks', via: :put, as: "handle_listRisks"
  match 'list_risks' => 'risks#list_risks', via: :post, as: 'list_risks'

  match 'audits', to: 'audits#handle_audit_status', via: :put, as: :handle_audit_status
  match 'list_audits' => 'audits#list_audits', via: :post, as: 'list_audits'
  match 'audits/:id/result' => 'audits#result', via: :get, as: 'result'
  match "start_audit" => "audits#start_audit", via: :post, as: 'start_audit'

  get 'home/index'

  resources :home, only: [:index] do
    member do
      post :mark_as_read
    end
    collection do
      put :save_audit_action, as: :save_audit_action
    end
  end

  get 'dashboard/index'
  match "audit_this_year" => "dashboard#audit_this_year", via: :get, as: 'audit_this_year'
  match "topic_risk_trend" => "dashboard#topic_risk_trend", via: :get, as: 'topic_risk_trend'
  match "document_status" => "dashboard#document_status", via: :get, as: 'document_status'
  match "audit_result" => "dashboard#audit_result", via: :get, as: 'audit_result'
  match "compliance_rate" => "dashboard#compliance_rate", via: :get, as: 'compliance_rate'

end

YourSOP/app/models/document.rb
class Document < ActiveRecord::Base
  acts_as_commontable


  
  belongs_to :user
  belongs_to :organisation
  has_many :approvals
  validates_presence_of :approvals

  has_many :reviews
  validates_presence_of :reviews

  has_many :readers
  has_many :trainees
  #validates_presence_of :trainees, message: "Sign off users can't be blank"
  belongs_to :topic

  has_many :risks_documents
  has_many :risks, through: :risks_documents

  belongs_to :document_topic


  has_many :document_revisions
  accepts_nested_attributes_for :document_revisions

  has_many :audits_practices_documents
  has_many :audits_practices, through: :audits_practices_documents
  

  # paperclip gem
  has_attached_file :doc, :storage => :s3, :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

  do_not_validate_attachment_file_type :doc     # TODO choose valid file types

  has_many :users, through: :approvals
  has_many :users, through: :readers
  has_many :users, through: :reviews
  #has_many :users, through: :trainees

  validates :title, presence: true, length: { maximum: 255 }
  validates :status, presence: true
  validates :review_date, presence: true
  #validate :check_document_review_date
  validates :content, presence: true, unless: 'doc.present?'
  #validates_presence_of :content

def check_document_review_date
  if self.review_date != nil 
   if self.review_date < Date.today 
      errors.add(:review_date, " Can't be less than today")
   end
  end
end


def s3_credentials
  # Adding this new line
 {:bucket => "saasproject", :access_key_id => "", :secret_access_key => ""}
end 
  

end

YourSOP/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  require 'htmlentities'    # decode encoded HTML tags from diff output

  @@STATUS_DRAFT = 0    # document status filter values for list in index view
  @@STATUS_FOR_REVIEW = 1
  @@STATUS_FOR_APPROVAL = 2
  @@STATUS_APPROVED = 3
  @@STATUS_TRAINING = 4

  before_action :check_current_organisation

  def index
    @documents = get_filtered_documents # view draft documents by current user default
    @my_documents = get_signed_documents
    @current_user = current_user
  end

  def show
    setup_show
  end

  def new
    #everyone should be able to create docs
    #if is_basic(OrganisationUser.where(organisation: get_current_organisation, user: current_user)[0].user_type)
    #  redirect_to :documents, notice: 'Basic user accounts cannot create documents.'
    #end

    @document = Document.new
    @document.document_revisions.build
    setup_new
  end

  def create
    @document = Document.new(document_params)
    @document.organisation = get_current_organisation
    @document.status = @@STATUS_DRAFT

    @document.major_version = "0"
    @document.minor_version = "1"
    @document.do_update = false
    @document.change_control = "Initial creation."
    
    if draft?
      @document.status = 0
    else
      @document.status = 1
    end

    if params[:reviews] != nil
      new_reviewer_ids = params[:reviews]
      new_reviewer_ids.each do |blah, action|
        next if blah.blank?
        blah2 = Review.new
        blah2.user_id = blah.to_i
        blah2.status = 0
        blah2.major_version = @document.major_version
        blah2.minor_version = @document.minor_version
        @document.reviews << blah2
      end
    end

    if params[:approvals] != nil
      new_approver_ids = params[:approvals]
      new_approver_ids.each do |blah, action|
        next if blah.blank?
        blah2 = Approval.new
        blah2.user_id = blah.to_i
        blah2.status = 0
        blah2.major_version = @document.major_version
        blah2.minor_version = @document.minor_version
        @document.approvals << blah2
      end
    end

    if params[:trainees] != nil
      new_traineer_ids = params[:trainees]
      new_traineer_ids.each do |blah, action|
        next if blah.blank?
        blah2 = Trainee.new
        blah2.user_id = blah.to_i
        blah2.status = 0
        blah2.major_version = @document.major_version
        blah2.minor_version = @document.minor_version
        @document.trainees << blah2
      end
    end

    saved = false
    if draft? 
      saved = @document.save!(:validate => false)
    else
      saved = @document.save
      # send mail
      if saved
        send_initial_mail
      end
    end

    if saved
      # continue, create relations
    else
      setup_new
      render action: 'new', alert: 'Document could not be created'
      return
    end    

    if params[:document][:assigned_to_all] != nil
      if params[:readers] != nil
        new_reader_ids = params[:readers]
        new_reader_ids.each do |id, action|
          next if id.blank?
          r = Reader.new
          r.user_id = id.to_i
          r.document = @document
          r.save
        end
      end
    end
  	
    if draft?
      msg = 'Document was successfully saved.'
    else
      msg = 'Document was successfully created.'
    end

    redirect_to action: 'index', notice: msg
  end

  def edit
    @document = Document.find(params[:id])
    if @document.user != current_user
      flash[:warning] = 'You can only edit documents created by you.'
      redirect_to action: 'index'
    end
    if @document.status != 0
      flash[:warning] = 'You can only edit documents that are in the Draft state.'
      redirect_to action: 'index'
    end
    setup_edit
  end

  def revise
     @document = Document.find(params[:id])
    if @document.user != current_user
      flash[:warning] = 'You can only revise documents created by you.'
      redirect_to action: 'index'
    end

    if @document.status != @@STATUS_APPROVED
      flash[:warning] = 'You can only revise documents that are in the Effective state.'
      redirect_to action: 'index'
    end
    setup_edit
  end

  def update
    @document = Document.find(params[:id])

    if @document.do_update == true and draft? == false
      @document_revision = DocumentRevision.new(major_version: @document.major_version, minor_version: @document.minor_version, content: @document.content,
                                                change_control: @document.change_control, document_id: @document.id)
      # minor verison + 1
      minor_version = (@document.minor_version.to_i + 1).to_s
      @document.update(minor_version: minor_version, do_update: false)
      @document_revision.save
    end

    reviews =  @document.reviews.find_by_document_id_and_major_version_and_minor_version(@document.id, @document.major_version, @document.minor_version)
    if reviews.present?
      reviews.destroy
    end

    approvals = @document.approvals.find_by_document_id_and_major_version_and_minor_version(@document.id, @document.major_version, @document.minor_version)
    if approvals.present?
      approvals.destroy
    end
    
    users = @document.trainees.find_by_document_id_and_major_version_and_minor_version(@document.id, @document.major_version, @document.minor_version)
    if users.present?
      users.destroy
    end

    @document.reload

    if params[:reviews] != nil
      new_reviewer_ids = params[:reviews]
      new_reviewer_ids.each do |blah, action|
        next if blah.blank?
        blah2 = Review.new
        blah2.user_id = blah.to_i
        blah2.status = 0
        blah2.major_version = @document.major_version
        blah2.minor_version = @document.minor_version
        @document.reviews << blah2
      end
    end

    if params[:approvals] != nil
      new_approver_ids = params[:approvals]
      new_approver_ids.each do |blah, action|
        next if blah.blank?
        blah2 = Approval.new
        blah2.user_id = blah.to_i
        blah2.status = 0
        blah2.major_version = @document.major_version
        blah2.minor_version = @document.minor_version
        @document.approvals << blah2
      end
    end

    if params[:trainees] != nil
      new_traineer_ids = params[:trainees]
      new_traineer_ids.each do |blah, action|
        next if blah.blank?
        blah2 = Trainee.new
        blah2.user_id = blah.to_i
        blah2.status = 0
        blah2.major_version = @document.major_version
        blah2.minor_version = @document.minor_version
        @document.trainees << blah2
      end
    end

    saved = false
    if draft? 
      saved = @document.update_columns(document_params)
    else
      saved = @document.update(document_params.merge(:status => 1))
      if saved
        send_initial_mail
      end
    end

    if saved
      flash[:success] = 'Document was successfully updated.'
      redirect_to action: 'show'
    else
      setup_edit
      flash[:danger] = 'Document could not be updated.'
      render action: 'edit'
    end

  end

  def compare
    @document = Document.find(params[:id])
    @html_diff = ''

    if params[:revision1] == params[:revision2]
      flash[:danger] = 'You cannot compare a document revision to itself.'
      redirect_to document_path @document.id
      return
    end

    # check for revision id == 0 (current revision)
    # older revision has lower DocumentRevision id
    if params[:revision1] == '0'
      @older_revision = DocumentRevision.find(params[:revision2])
      @newer_revision = @document
    elsif params[:revision2] == '0'
      @older_revision = DocumentRevision.find(params[:revision1])
      @newer_revision = @document
    else
      if params[:revision1].to_i < params[:revision2].to_i    # revision 1 id is smaller, it is an older revision
        @older_revision = DocumentRevision.find(params[:revision1])
        @newer_revision = DocumentRevision.find(params[:revision2])
      else
        @older_revision = DocumentRevision.find(params[:revision2])
        @newer_revision = DocumentRevision.find(params[:revision1])
      end
    end

    @html_diff = get_html_diff @older_revision, @newer_revision
  end

  def revision
    @document = Document.find(params[:id])
    @document_revisions = DocumentRevision.where(document_id: @document.id).order(id: :desc)
    @revision = DocumentRevision.find_by_document_id_and_major_version_and_minor_version params[:id], params[:major], params[:minor]
    if @revision == nil
      setup_show
      flash[:warning] = "#{@document.title} revision #{params[:major]}.#{params[:minor]} was not found."
      redirect_to document_path(params[:id])
    end
  end


  def revert_to_draft
    if (params[:id] == nil) 
      return
    end

    document = Document.find(params[:id].to_i)
    if document.user_id != current_user.id || document.status != @@STATUS_APPROVED
      flash[:danger] = 'You cannot perform this operation.'
      redirect_to documents_path
    end
    document_revision = DocumentRevision.new(major_version: document.major_version, minor_version: document.minor_version, content: document.content,
                                                change_control: document.change_control, document_id: document.id)
    minor_version = (document.minor_version.to_i + 1).to_s
    document.update(minor_version: minor_version, status: @@STATUS_DRAFT, do_update: false)
    document_revision.save

    flash[:success] = 'You have reverted this document to draft.'
    render :js => "window.location = '/documents'"
  end

  # handle 'Approve/Decline/Mark as reviewed' button click in document show view
  def save_role_response
    if params[:decline] == nil    # require a digital signature to approve/mark as reviewed
      # password is filtered in params log by Devise gem (not visible in params array)
      if params[:email] != current_user.email || !current_user.valid_password?(params[:password])   # if wrong email or password

YourSOP/app/helpers/documents_helper.rb
module DocumentsHelper
  def status_to_string status
    if status == 0
      "Draft"
    elsif status == 1
      "For review"
    elsif status == 2
      "For approval"
    elsif status == 3
      "Effective"
    else
      "Unknown"
    end
  end

  def approval_status_to_string status, updated_at
    if status == 0
      'Pending'
    elsif status == 1
      'Approved(' + updated_at.to_s + ')'
    elsif status == 2
      'Declined(' + updated_at.to_s + ')'
    elsif status == 3
      'Canceled'
    else
      'Unknown'
    end
  end

  def review_status_to_string status, updated_at
    if status == 0
      'Pending'
    elsif status == 1
      updated_at.to_s
    else
      'Unknown'
    end
  end

  def trainee_status_to_string status, updated_at
    if status == 0
      'Pending'
    elsif status == 1
      updated_at.to_s
    else
      'Unknown'
    end
  end

  def get_document_version document
    "#{document.major_version}.#{document.minor_version}"
  end

  def get_effective_document_version document
    "#{document.major_version}.0"
  end

end

YourSOP/app/views/documents/_list.erb
<br />
    <table class="table tablesorter">
      <thead>
      <tr>
        <th>
          Document
        </th>
        <th>
          Created By
        </th>
        <th>
          Created
        </th>
        <th>
          Updated
        </th>
        <th>
          Topic
        </th>
        <th>
          Status
        </th>
        <th>
          Version
        </th>
        <th>
          Review Date
        </th>
        <th>
          Actions
        </th>
      </tr>
      </thead>
      <tbody>
      <% documents.each do |d| %>
          <tr>
            <td>
              <%= link_to d.title, document_path(d.id) %>
            </td>
            <td>
              <%= d.user.name %>
            </td>
            <td>
              <%= d.created_at %>
            </td>
            <td>
              <%= d.updated_at %>
            </td>
            <td>
              <% if d.topic == nil %>
                Unspecified
              <% else %>
                <%= d.topic.name %>
              <% end%>
            </td>
            <td>
              <%= status_to_string d.status %>
            </td>
            <td>
              <%= d.major_version %>.<%= d.minor_version %>
            </td>
            <td>
              <%= d.review_date %>
            </td>
            <td>
              <%= link_to "Edit", edit_document_path(:id => d.id), :class => "btn-link" if d.status == 0 and d.user_id == @current_user.id %>
              <%= link_to "Review", document_path(:id => d.id), :class => "btn-link" if d.status == 1 and d.reviews.where(status: 0,  user_id: @current_user.id).count > 0 %>
              <%= link_to "Approve", document_path(:id => d.id), :class => "btn-link" if d.status == 2 and d.approvals.where(status: 0,  user_id: @current_user.id).count > 0 %>
              <%= link_to "Sign Off", document_path(:id => d.id), :class => "btn-link" if d.status == 3 and d.trainees.where(status: 0,  user_id: @current_user.id).count > 0 %>
                <%= link_to "Revert To Draft", revert_to_draft_path(:id => d.id), method: :post, remote: true, data: { confirm: 'Are you sure to revert this document to draft?' }, :class => "btn-link" if d.status == 3 and d.user_id == @current_user.id  %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>

YourSOP/app/views/documents/dashboard.erb
<h1>Documents#dashboard</h1>

YourSOP/app/views/documents/index.html.erb
<h1>SOPs</h1>
<%if !@current_user_is_basic %>
    <form action="<%= new_document_path %>">
      <button type="submit" class="btn btn-success" style="float: right;">Create New</button>
    </form>
    <br />
<% end %>



<!-- tab content -->
<div class="col-md-12 tabbable">
  <ul class="nav nav-tabs product-details-nav" id="document_filter_buttons">
    <li id="allDocFilter" role="presentation" class="active" <%= selected_document_filter if @initial_document_filter == "all_documents" %>><%= link_to "All SOPs", "#" %></li>
    <li id="yourDocFilter" role="presentation" <%= selected_document_filter if @initial_document_filter == "your_documents" %>><%= link_to " SOPs Signed By Me", "#" %></li>
  </ul>
  <div class="tab-content product-detail-info">
    <div class="tab-pane  active" id="tab0">
      <%= render partial: 'list', locals: {documents: @documents} %>    
    </div>

    <div class="tab-pane text-style" id="tab1">
      <%= render partial: 'mylist', locals: {documents: @my_documents} %>    
    </div>
  </div>
</div>

YourSOP/app/views/documents/revision.html.erb
<%= render partial: 'revision_heading', locals: {document: @document, revision: @revision} %>
<br /><br />

<% if !@document_revisions.empty? %>
    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        Compare to another revision
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= compare_path @document.id, 0, @revision.id %>"><%= get_document_version @document %> (current)</a></li>
        <% @document_revisions.each do |rev| %>
            <% if rev.id != @revision.id %>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= compare_path @document.id, rev.id, @revision.id %>"><%= get_document_version rev %></a></li>
            <% end %>
        <% end %>
      </ul>
    </div>
<% end %>

<hr />

<p>
  <strong>Change Control Message:</strong><br />
  <%= @revision.change_control %>
</p>

<br />

<p>
  <b>Document content: </b>
  <% if @document.content.blank? %>
      <%= link_to "Download document", @revision.doc.url(:original, false) %> (current version, uploaded revision not implemented)
  <% else %>
    <div class="well">
      <%= @revision.content.html_safe %>
    </div>
  <% end %>
</p>

YourSOP/app/views/documents/show.erb
<h1><%= @document.title %> <small>(Revision <%= get_document_version @document %>)</small></h1>

<% if @user == @document.user  && @document.status == 0%>
    <%= link_to 'Edit', edit_document_path(@document.id), class:"btn btn-warning" %>
    <%= link_to 'Delete', @document, method: :delete, data: { confirm: 'Are you sure you want to delete this document?' }, class:"btn btn-danger" %>
<% end %>

<br />


<% if !@document_revisions.empty? %>
    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        Compare to a previous revision
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        <% @document_revisions.each do |rev| %>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= compare_path @document.id, rev.id, 0 %>"><%= get_document_version rev %></a></li>
        <% end %>
      </ul>
    </div>
<% end %>

<hr />

<!-- Separate document information by tabs -->
<div id="bs-component" class="tabbable">
  <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
    <% if @document.doc_content_type == "application/pdf" %>
      <li class="active"><a href="#document_preview" data-toggle="tab">Preview</a></li>
      <li class=""><a href="#document_content" data-toggle="tab">View SOP</a></li>
    <% else %>
      <li class="active"><a href="#document_content" data-toggle="tab">View SOP</a></li>
    <% end %>
  
    <li><a href="#document_assigned_users" data-toggle="tab">Compliance Info</a></li>
  </ul>

  <div id="my-tab-content" class="tab-content product-detail-info">
    <% if @document.doc_content_type == "application/pdf" %>
    <br />  
        <div class="tab-pane fade in active" id="document_preview">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="/pdfjs/web/viewer.html?file=<%= @document.doc.url.sub('http', 'https') %>" ></iframe>
          </div>    
        </div>    
    <% end %>
    <% active = @document.doc_content_type == 'application/pdf' ? "" : "in active" %>

    <div class="tab-pane fade <%= active  %>" id="document_content">
      <% if @document.doc_content_type != nil %>
          <%= link_to "Download document", @document.doc.url(:original, false) %>
      <% else %>
          <%= @document.content.html_safe%>
      <% end %>
    </div>

    <div class="tab-pane fade" id="document_assigned_users">
      <div class="row">
           <br />
           <dl class="dl-horizontal">    
            <dt>SOP Status: </dt>
            <dd><%= status_to_string @document.status %></dd>
          </dl>
           <dl class="dl-horizontal">    
            <dt>COMPLIANCE: </dt>
            <dd 
            <% if @compliance_status == "NOT COMPLIANT" %>
             class="btn-red"
            <% end %>
            ><%= @compliance_status %></dd>
            
          </dl>
      </div>

      <div class="row">
        <div class="col-sm-6">
          <br />
           <h3>Staff Sign Off:</h3>
          <table class="table">
            <tr>
              <th>Staff</th>
              <th>Status</th>
            </tr>
            <% @trainee_users.each do |t| %>
            <tr>
              <td><%= t[:user].name %></td>
              <td 
               <% if t[:trainee].status != 1 %>
                 class="btn-red"
                <% end %>
              ><%= trainee_status_to_string t[:trainee].status, t[:trainee].updated_at %></td>
            </tr>
            <% end %>
          </table>
        </div>
        <div class="col-sm-6"></div>
      </div>
      
      <div class="row">
        <div class="col-sm-6">
          <br />
          <h3>Reviews</h3>
           <table class="table">
            <tr>
              <th>Staff</th>
              <th>Status</th>
            </tr>
             <% @review_users.each do |r| %>
              <tr>
                <td><%= r[:user].name %></td>
                <td 
                 <% if r[:review].status != 1 %>
                 class="btn-red"
                <% end %>
                ><%= review_status_to_string r[:review].status, r[:review].updated_at %></td>
              </tr>
              <% end %>
          </table>
        </div>
  
        <div class="col-sm-6">
          <br />
          <h3>Approvals</h3>
          <table class="table">
            <tr>
              <th>Staff</th>
              <th>Status</th>
            </tr>
             <% @approval_users.each do |a| %>
              <tr>
                <td><%= a[:user].name %></td>
                <td
                 <% if a[:approval].status != 1%>
                 class="btn-red"
                <% end %>
                ><%= approval_status_to_string a[:approval].status, a[:approval].updated_at %></td>
              </tr>
              <% end %>
          </table>
        </div>

      </div>

      <div class="row">
        <p>
          Created by: <%= @user.name %> <br />
          Created at: <%= @document.created_at %> <br />
          Reviewed: <%= @document.review_date %>
        </p>
      </div>

      <div class="row">
         <br />
        <h3>Previous Versions</h3>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>
                Revision Number
              </th>
              <th>
                Change Control Message
              </th>
              <th>
                Contents
              </th>
            </tr>
          </thead>

          <tbody>
            <% @document_revisions.each do |doc_revision| %>
              <tr>
                <td><%= get_document_version doc_revision %></td>
                <td><%= truncate(doc_revision.change_control, :length => 120) %></td>
                <td><%= link_to 'View', revision_path(doc_revision.document_id, doc_revision.major_version, doc_revision.minor_version) %></td>
              </tr>
            <% end %>
          </tbody>
        </table> 
      </div>

      <div class="row">
         <br />
          <%= commontator_thread(@document) %>
      </div>

    </div>

  </div>
</div>

<% if @is_reviewer || @is_approver || @is_traineer%>
    <hr />

    <%= form_tag 'save_role_response', method: :put do %>
        <%= hidden_field_tag :id, @document.id %>
        <%= hidden_field_tag :relation_id, @relation_id %>
        <!-- Button trigger modal -->
        <% if @is_reviewer %>
            <%= @document.user.name %> has assigned you to review this document.
            <% if @review.status == 0 %>
                You have not yet reviewed this document.
            <% end %>
            <br /><br />
            <% if @review.status != 1 %>
                <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal">
                  Mark as reviewed
                </button>
            <% else %>
                You have already marked this document as reviewed.
            <% end %>
        <% elsif @is_approver %>
            <%= @document.user.name %> has assigned you to approve this document.
            <% if @approval.status == 0 %>
                You have not yet approved or declined this document.
            <% end %>
            <br /><br />
            <% if @approval.status != 1 %>
                <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal">
                  Approve
                </button>
            <% else %>
                You have already approved this document.
            <% end %>
            <% if @approval.status != 2 %>
                <input type="submit" class="btn btn-danger btn-lg" value="Decline document" name="decline" />
            <% else %>
                You have already declined this document.
            <% end %>
        <% elsif @is_traineer && @document.status == 3 && @trainee.status == 0 %>
            <!--%= @trainee.status%-->
            <%= @document.user.name %> has assigned you to do the sign off to comply with this document.
            <% if @trainee.status == 0 %>
                You have not signed off yet.
            <% end %>
            <br /><br />
            <% if @trainee.status != 1 %>
                <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal">
                  Agree and sign off
                </button>
            <% else %>
                You have signed off to comply with this document.
            <% end %>
        <% end %>
    <% end %>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">
              <% if @is_reviewer %>
                  Mark as reviewed
              <% elsif @is_approver %>
                  Approve
              <% else %>
                  Agree to be compliant
              <% end %>
            </h4>
          </div>

          <div class="modal-body">
            <% if @is_reviewer %>
                I have reviewed this document.
            <% elsif @is_approver%>
                I approve this document.
            <% else %>
                I have read the document
            <% end %>
            <br />
            <%= bootstrap_form_tag url: 'save_role_response', method: :put do |f| %>
                <%= f.hidden_field :id, value: @document.id %>
                <%= f.hidden_field :relation_id, value: @relation_id %>
                <%= f.text_field(:email, value: @current_user.email) %>
                <%= f.password_field(:password) %>
                <br />
                <br />
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <% if @is_reviewer %>
                      <input type="submit" class="btn btn-success" value="Mark document as reviewed" name="review" />
                  <% elsif @is_approver %>
                      <input type="submit" class="btn btn-success" value="Approve document" name="approve" />
                  <% else %>
                      <input type="submit" class="btn btn-success" value="Agree to document" name="train" />
                  <% end %>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

<% end %>