YourSOP/config/routes.rb
Rails.application.routes.draw do

  resources :topics

  resources :organisations do
    collection do
      get :invite
      get :users
      delete :remove_user
      get :edit_user
      put :update_user
      get :services
      put :update_service
      get :import
      put :update_sops
      get :browse
    end
    put :save_current_organisation#, :on => :collection

    get :autocomplete_user_email, :on => :collection
  end

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users

  resources :documents do
    collection do
      put :save_role_response, as: :save_role_response
    end
  end

  resources :risks

  resources :audits do
    collection do
      put :save_audit_response, as: :save_audit_response
    end
  end

  resources :topics

  get 'documents/index'
  get 'documents/dashboard'
  match 'documents', to: 'documents#handle_status', via: :put, as: :handle_status
  match 'documents/:id/revise' => 'documents#revise', via: :get, as: 'revise'

  match 'organisations/save_current_organisation', to: 'organisations#save_current_organisation', via: :post
  
  match "organisations/accept_organisation_invitation", to: 'organisations#accept_organisation_invitation', via: :post
  match "organisations/decline_organisation_invitation", to: 'organisations#decline_organisation_invitation', via: :post

  match "organisations/accept_organisation_application", to: 'organisations#accept_organisation_application', via: :post
  match "organisations/decline_organisation_application", to: 'organisations#decline_organisation_application', via: :post

  match 'organisations/invite', to: 'organisations#inviteSubmission', via: :post
  match 'organisations/join/:id' => 'organisations#join', via: :get

  match "revert_to_draft" => "documents#revert_to_draft", via: :post, as: 'revert_to_draft'

  root to: "home#index"

  match 'documents/:id/revision/:major-:minor' => 'documents#revision', via: :get, as: 'revision'

  match 'documents/:id/compare/:revision1/:revision2' => 'documents#compare', via: :get, as: 'compare'

  mount Commontator::Engine => '/commontator'

  get 'risks/index'
  match 'risks', to: 'risks#handle_listRisks', via: :put, as: "handle_listRisks"
  match 'list_risks' => 'risks#list_risks', via: :post, as: 'list_risks'

  match 'audits', to: 'audits#handle_audit_status', via: :put, as: :handle_audit_status
  match 'list_audits' => 'audits#list_audits', via: :post, as: 'list_audits'
  match 'audits/:id/result' => 'audits#result', via: :get, as: 'result'
  match "start_audit" => "audits#start_audit", via: :post, as: 'start_audit'

  get 'home/index'

  resources :home, only: [:index] do
    member do
      post :mark_as_read
    end
    collection do
      put :save_audit_action, as: :save_audit_action
    end
  end

  get 'dashboard/index'
  match "audit_this_year" => "dashboard#audit_this_year", via: :get, as: 'audit_this_year'
  match "topic_risk_trend" => "dashboard#topic_risk_trend", via: :get, as: 'topic_risk_trend'
  match "document_status" => "dashboard#document_status", via: :get, as: 'document_status'
  match "audit_result" => "dashboard#audit_result", via: :get, as: 'audit_result'
  match "compliance_rate" => "dashboard#compliance_rate", via: :get, as: 'compliance_rate'

end

YourSOP/app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>YourSOP 1.0</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,800' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Navigation & Logo-->
    <div class="mainmenu-wrapper">
      <div class="container">
        <div class="menuextras">
          <div class="extras">
            <ul>
               <% if !user_signed_in? %>
                <!-- <li><a href="/users/sign_in">Login</a></li> -->
              <% end %>
            </ul>
          </div>
        </div>
      <nav id="mainmenu" class="mainmenu">
      <ul>
        <li class="logo-wrapper">
          <a href="/">YourSOP</a>
        </li>

        <% if user_signed_in? %>

          <li class="<% if controller?("documents") %> <%= 'active'%> <% end %>">
            <a href="<%= documents_path %>">SOPs <span class="sr-only">(current)</span></a>
          </li>

           <% if if_current_user_is_quality && false %>
              <li class="<% if controller?("risks") %> <%= 'active'%> <% end %>"><a href="<%= risks_path %>">Topics <span class="sr-only">(current)</span></a></li>
            <% end %>
            <!-- <li class="<% if controller?("audits") %> <%= 'active'%> <% end %>"><a href="<%= audits_path %>">Audits <span class="sr-only">(current)</span></a></li> -->
            <li class="<% if controller?("dashboard") %> <%= 'active'%> <% end %>"><a href="/dashboard/index">Compliance <span class="sr-only">(current)</span></a></li>

            <ul class="nav navbar-nav navbar-right">
              <% if @current_organisation != nil %>
                  <li><%= link_to @current_organisation.name, organisations_path %></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                      Settings
                      <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                      <% if @current_user_is_owner %>
                        <% if @current_organisation.id != 1 %>
                          <li><%= link_to 'Services', services_organisations_path %></li>       
                        <% end %>                   
                          <li><%= link_to 'Staff Management', users_organisations_path %></li>
                      <% else %>
                          <li><%= link_to 'View Staffs', users_organisations_path %></li>
                      <% end %>
                      <% if if_current_user_is_quality %>
                          <li><%= link_to 'Manage Topics', topics_path %></li>
                      <% end %>
                    </ul>
                  </li>
                  <% end %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Welcome, <%= current_user.name %>
                    <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><%= link_to 'Edit profile', main_app.edit_user_registration_path %></li>
                      <li>
                        <%= link_to 'Sign out', '/users/sign_out', method: 'delete' %>
                      </li>
                    </ul>
                  </li>
                  
            <% end %>
            </ul>
            <% if @current_organisation != nil %>

              <div class="progress">
                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="<%= @compliance_rate%>"
                aria-valuemin="0" aria-valuemax="100" style="width:<%= @compliance_rate %>%">
                  <%= @compliance_rate %>%
                </div>
              </div>
            <% end %>
          </nav>
      </ul>
    </nav>
  </div>
</div>

<div class="section">
    <div class="container">
      <%= yield %>
    </div>
</div>



<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-footer col-md-3 col-xs-6">
        <h3>About YourSOP</h3>
       <!--  <div class="portfolio-item">
          <div class="portfolio-image">
            <a href="page-portfolio-item.html"><img src="img/portfolio6.jpg" alt="Project Name"></a>
          </div>
        </div> -->
      </div>
      <div class="col-footer col-md-3 col-xs-6">
        <h3>Navigate</h3>
        <ul class="no-list-style footer-navigate-section">
          <li><a href="#">Blog</a></li>
          <li><a href="#">FAQ</a></li>
        </ul>
      </div>
      
      <div class="col-footer col-md-4 col-xs-6">
        <h3>Contacts</h3>
        <p class="contact-us-details">
            <b>Address:</b> 123 AAA Street, Cork, Ireland<br/>
            <b>Phone:</b> +11 1111 1111<br/>
            <b>Fax:</b> +11 1111 1111<br/>
            <b>Email:</b> <a href="mailto:YourSOP@YourSOP.com">YourSOP@YourSOP.com</a>
          </p>
      </div>
      <div class="col-footer col-md-2 col-xs-6">
        <h3>Stay Connected</h3>
        <ul class="footer-stay-connected no-list-style">
          <li><a href="#" class="facebook"></a></li>
          <li><a href="#" class="twitter"></a></li>
          <li><a href="#" class="googleplus"></a></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="footer-copyright">&copy; 2015 YourSOP. All rights reserved.</div>
      </div>
    </div>
  </div>
</div>

</body>
</html>